spring.application.name=opc
server.port=8080

com.xiaomizhou.dpsk.base-path=C:/Users/Administrator/.dpsk
com.xiaomizhou.dpsk.file.upload.path=${com.xiaomizhou.dpsk.base-path}/uploads
com.xiaomizhou.dpsk.file.host=http://127.0.0.1:${server.port}/

spring.web.resources.static-locations=${com.xiaomizhou.dpsk.base-path}/uploads
spring.mvc.static-path-pattern=/uploads/**
spring.web.resources.cache.period=3600

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:${com.xiaomizhou.dpsk.base-path}/db/opc;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.username=root
spring.datasource.password=test

# SQL 初始化配置
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema/schema.sql
spring.sql.init.continue-on-error=false
mybatis-plus.mapper-locations=classpath:db/mapper/*.xml

com.xiaomizhou.opc.llm.api-key=sk-0803dabfa90b4a188e116e007f442a62
com.xiaomizhou.opc.llm.base-url=https://api.deepseek.com/v1
com.xiaomizhou.opc.llm.model-name:deepseek-chat


com.xiaomizhou.dpsk.opc.rag.jvector.data-path=${com.xiaomizhou.dpsk.base-path}/db/rag/jvector
com.xiaomizhou.dpsk.opc.knowledge.build.cron=0 3/5 * * * ?

# logging.level.com.xiaomizhou.dpsk.db.mapper=debug

