server.port=8081
spring.application.name=opc

com.xiaomizhou.dpsk.agent.registry.type=local
com.xiaomizhou.dpsk.agent.root.path=W:\\uat
com.xiaomizhou.dpsk.file.upload.path=W:\\uat\\uploads
com.xiaomizhou.dpsk.file.access.prefix=/xiaomizhou/opc/v1/file/download
com.xiaomizhou.dpsk.db.path=W:\\uat\\db

spring.ai.openai.api-key=sk-0803dabfa90b4a188e116e007f442a62
spring.ai.openai.api-base-url=https://api.openai.com/v1
spring.ai.openai.api-model=deepseek-chat


# 文件上传存储路径（使用 file:/// 前缀格式）
spring.web.resources.static-locations=W:\\uat\\uploads

# 设置静态资源请求路径前缀（/uploads/** -> W:\tmp\uploads）
spring.mvc.static-path-pattern=/uploads/**

# 设置缓存时间（可选，单位秒）
spring.web.resources.cache.period=3600

spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:./db/opc;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL
spring.datasource.username=root
spring.datasource.password=test

# SQL 初始化配置
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:db/schema/schema.sql
spring.sql.init.continue-on-error=false
mybatis-plus.mapper-locations=classpath:db/mapper/*.xml

